version: "3.9"

services:
  backend:
    build:
      context: .  
    ports:
      - "8000:8000"
    env_file:
      - .env  
    networks:
      - kyc-network

  frontend:
    build:
      context: ../frontend  
    ports:
      - "3000:3000"
    networks:
      - kyc-network

networks:
  kyc-network:
