version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - kyc-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - kyc-network

  db:
    build:
      context: ./database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: kyc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kyc-network

networks:
  kyc-network:

volumes:
  postgres_data:
